version: "3.8"
services:
  frontend:
    hostname: client
    restart: always
    image: node:18-alpine
    container_name: learn-app-frontend
    command: sh -c "cd /f-app && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./apps/www/client:/f-app

  backend:
    hostname: backend
    restart: always
    image: node:18-alpine
    container_name: learn-app-backend
    command: sh -c "cd /b-app && yarn start:dev"
    ports:
      - 3005:3005
    depends_on:
      - db
    volumes:
      - ./end:/b-app

  db:
    container_name: learn-app-db
    hostname: db
    restart: always
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=learnAppDB
      - POSTGRES_DB=learn_app
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
